### ISSUE TITLE
Report imagemagick dirty exit and don't crash.

### ISSUE THREAD

**Issue by kilianc** [kilianc/adobe-generator#65]
We need to get stderr

```
11/28/201208: 56: 04: {
  "message": "Command failed: ",
  "stack": "Error: Command failed: 
      at ChildProcess.<anonymous> (/Users/timriot/Desktop/Motherlover.app/Contents/Resources/server/node_modules/imagemagick/imagemagick.js:88:15)
      at ChildProcess.EventEmitter.emit (events.js:99:17)
      at maybeClose (child_process.js:638:16)
      at Socket.ChildProcess.spawn.stdin (child_process.js:815:11)
      at Socket.EventEmitter.emit (events.js:96:17)
      at Socket._destroy.destroyed (net.js:357:10)
      at process.startup.processNextTick.process._tickCallback (node.js:244:9)",
  "code": "UNCAUGHT_EXCEPTION"
}
```

**Comment by kilianc** [comment]
done
