### ISSUE TITLE
Random crash on asset dump

### ISSUE THREAD

**Issue by kilianc** [kilianc/adobe-generator#71]
It seems that sometimes ps doesn't return the pixmap.
# investigating probably related to #68

```
{
  "message": "Cannot read property 'buffer' of null",
  "stack": "TypeError: Cannot read property 'buffer' of null
      at Object.callback (/Users/timriot/Desktop/Motherlover.app/Contents/Resources/server/server.js:116:35)
      at dispatchMessage (/Users/timriot/Desktop/Motherlover.app/Contents/Resources/server/lib/photoshop.js:293:57)
      at Photoshop.fillPayload (/Users/timriot/Desktop/Motherlover.app/Contents/Resources/server/lib/photoshop.js:271:7)
      at Photoshop.readMessageLength (/Users/timriot/Desktop/Motherlover.app/Contents/Resources/server/lib/photoshop.js:244:8)
      at Socket.g (events.js:192:14)
      at Socket.EventEmitter.emit (events.js:96:17)
      at TCP.onread (net.js:396:14)",
  "code": "UNCAUGHT_EXCEPTION"
}
```

**Comment by kilianc** [comment]
Tested on an iMac without the developer suite (Snow Lion from App Store)
An it works with every file you dropped to me @timriot.

We need a p2p debug session.

**Comment by timriot** [comment]
operator error. I had the incorrect build.
